### ISSUE TITLE
node sass failing after install

### ISSUE THREAD

**Issue by djalbat** [sass/node-sass#1396]
Hi,

I get this error when I try to require('node-sass-middleware');

Error: The `libsass` binding was not found in /home/james/Development/Florence/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/james/Development/Florence/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/james/Development/Florence/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/james/Development/Florence/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:409:26)

Process finished with exit code 1

Some info for you:

npm -v 3.7.5
node -v v5.6.0
node -p process.versions
{ http_parser: '2.6.1',
  node: '5.6.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2f' }

node -p process.platform  linux
node -p process.arch  x64

/node_modules/.bin/node-sass --version
  node-sass	3.4.2	(Wrapper)	[JavaScript]
  libsass  	3.3.2	(Sass Compiler)	[C/C++]

node -p "console.log(require('node-sass').info)"
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
undefined

I tried npm rebuild node-sass but it doesn't fix this.

I have vendor/linux-x64-47/binding.node but not ...-46/...
 
Regards

**Comment by xzyfer** [comment]
This is because you run npm install on node 5 (47) but your trying to load
you code in node 4 (46). Whenever you change node versions you should
either remove your node_modules folder and reinstall, or rebuild your
native extension.

The error message you posted tells you how to fix this issue. I'll leave it
as an exercise for you to read the error message.

**Comment by djalbat** [comment]
Hi,

>The error message you posted tells you how to fix this issue..

I read the error message and tried have tried this already, as I pointed out. I have also already tried deleting the node_modules directory and re-installing. I get the same message.

>This is because you run npm install on node 5 (47) but your trying to load
you code in node 4 (46)

Are you sure? I have:

npm -v 3.7.5
node -v v5.6.0

I don't know what you mean by 'your trying to load you code', it doesn't read as plain English to me.

**Comment by djalbat** [comment]
I've fixed the problem despite your comments.

I'll post the solution here in case anyone else encounters the same thing.

The latest version of node at /usr/bin/local/node, however there is a legacy version of node at /usr/bin/node, I have no idea why. Running my application from the command line works, because the latest version of node is being used. Running my application from within Webstorm does not, however, because it was configured to point at the old version of node. Fixing the configuration in Webstorm fixed the problem.

For the record I found your comments to be patronising and unhelpful. If you cannot bring yourself to at least be polite you should not be placed in front of end users, who's continued support of your software is the only reason you are there in the first place.

**Comment by xzyfer** [comment]
Your issue was being caused by having multiple versions of node install, v4
and v5.

Modules are installed against the version used when npm install runs. Npm
must've been using node 4 when installing modules. When you tried to the
run your code with node 5 the modules were incompatible.

The reason rebuilding didn't resolve your issue was because npm was running
the rebuild scripts with its older node. The rebuild output would have said
it was downloading the Node 4 (46) binary.

Something we can do in this space is translate module versions (45, 46...)
to human friendly node version numbers.
