### ISSUE TITLE
Error installing 1.1.4

### ISSUE THREAD

**Issue by gschwartzbard-ra** [sass/node-sass#497]
I am getting the following error when installing via npm install:

```
> node-sass@1.1.4 install /jenkins/jobs/webapp.order/workspace/node_modules/gulp-sass/node_modules/node-sass
> node build.js

`linux-x64-v8-3.14` exists; testing
make: Entering directory `/jenkins/jobs/webapp.order/workspace/node_modules/gulp-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory `/jenkins/jobs/webapp.order/workspace/node_modules/gulp-sass/node_modules/node-sass/build'
```

**Comment by odino** [comment]
Same issue here. Rollbacking to `1.2.3` "fixed" it for now...scary :)

**Comment by ferrybrouwer** [comment]
I've just wrote a fix for osx:
https://github.com/ferrybrouwer/node-sass-patch

**Comment by ysimonson** [comment]
I'm seeing this issue with 2.0.0-beta on mac os x. There's no `node-sass/build` directory, and the `node-sass/vendor` directory has an `darwin-x64` directory, but it's empty.

**Comment by skrobek** [comment]
I have te same issue as @ysimonson

**Comment by ysimonson** [comment]
@skrobek fwiw it seems to build fine on a fresh (newly reformatted) os x install.

**Comment by StoneCypher** [comment]
This works fine for me, but not for my coworker, as of today using up to date versions.  We do not yet know what the difference between our machines is.

We face the same apparent problem as @alfredbez .  Hard rolling back to `1.2.3` after torching `node_modules` did *not* resolve the problem for us.

My machine is /far/ newer than my coworker's.

**Comment by StoneCypher** [comment]
@andrew the data seems to suggest that the defect described here is not the defect in the linked ticket, and indeed, that the linked ticket describes more than one unrelated problem.

Are you certain this ticket should be closed?

**Comment by izolate** [comment]
+1 reopen. Getting ```Error: `libsass` bindings not found. Try reinstalling `node-sass`?```

**Comment by am11** [comment]
@izolate, this was superseded by https://github.com/sass/node-sass/issues/517, which has been resolved. If you are having further problems, please open a new issue with elaborate details like: which versions of npm, nodejs you have installed and which version of node-sass you are trying to install? Also see https://github.com/sass/node-sass/issues/635#issuecomment-71454680.

**Comment by StoneCypher** [comment]
This happens with a fresh install on a mac which never had the tools as of yesterday.  I'll gather the actual version numbers for you when that staff member comes in, but for all intents and purposes, it's node-current, npm-current, gulp-current, node-sass current, libsass current.

I'll get you the proper numbers as soon as I am able.

**Comment by jclif** [comment]
Getting this on a circleci build.

**Comment by saper** [comment]
@jclif please follow our [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide, and if that does not help please post the result. 

This bug pertains node-sass@1.1.4 which is very old and does not support current node engines. We still do not support io.js 3.0 #1053 at the time of writing this.

**Comment by waltonryan** [comment]
for those that might be having similar issues today, I resolved the problem by upgrading my node-sass-middleware
<pre>
npm uninstall node-sass-middleware --save //was 0.5.0
npm install node-sass-middleware --save //now 0.9.6
</pre>

I was facing the issue creating a node app with heroku and keystonejs.
