### ISSUE TITLE
update to libsass 3.2.0-beta.4

### ISSUE THREAD

**Issue by fsmanuel** [sass/node-sass#827]
Hey thanks for the great work.
I run into 'Support parent selector & in values / and/or interpolations' (https://github.com/sass/libsass/issues/548). That seems to be fixed in libsass `3.2.0-beta.4`.
Anything I can do to help with a new release that includes libsass `3.2.0-beta.4`?

**Comment by am11** [comment]
@fsmanuel, thanks for the offer. I have a very busy week going on. The only stopper is the recent changes in importer. I will try to spend sometime over the weekend.

@mgreter, here are the changes [I was referring](https://github.com/sass/libsass/issues/1020#issuecomment-88226575) to: https://github.com/am11/node-sass/commit/55aadd29ac006899be7972bc970ad3332f8e4b28. It throws at [line 11](https://github.com/am11/node-sass/commit/55aadd29ac006899be7972bc970ad3332f8e4b28#diff-672b939c4bdf28c42fc7ba5da56105dbR11) because `Sass_Compiler` (`comp`) is null with the following test:

```javascript
// in node-sass dir
require('./').render({
  data: '@import \'doesNotExist.scss\'',
  importer: function(url, prev, done) {
    done({file: url, contents: 's { a: ss; }'});
  }
}, function(err, result){
  if(err) {
    console.log(err); return;
  }

  console.log(result, result.css.toString());
});
```

(hopefully missing something fundamental and not the bug in libsass..)

Note this is the first step to make the previous implementation just work. Once this passes the existing test suite, I will modify it for multi importers support.

**Comment by OnkelTem** [comment]
+1
Can't wait to try libsass 3.2.0-beta4

**Comment by am11** [comment]
Libsass beta4 had a bug which is fixed in their master. We are waiting on the next nightly.

**Comment by am11** [comment]
v3.0.0-beta.5 is released pointing to libsass v3.2.0-beta.5: https://github.com/sass/node-sass/releases/tag/v3.0.0-beta.5.

**Comment by fsmanuel** [comment]
@am11 :+1:

**Comment by davidpaulsson** [comment]
Yay! Great work everyone

**Comment by OnkelTem** [comment]
Thanks! Much better now but still not quite working. Specifically, singularitygs doesn't compile yet due to using negative numbers in maps keys: https://github.com/sass/libsass/issues/1086
